org: hunlam
app: fullstack-test-serverless
service: fullstack-test-serverless

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    DB_HOST: fullstack-test-db.c5vjkdqazbna.us-east-1.rds.amazonaws.com
    DB_USERNAME: postgres
    DB_PASSWORD: FR9DQE6CwWtyvXdkAI1H
    DB_PORT: 5432
    DB_DATABASE: postgres

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

package:
  individually: true

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
